# Generated by Django 2.2.16 on 2022-10-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20221005_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_is_verified',
            field=models.BooleanField(default=False, verbose_name='Проверен ли е-мейл'),
        ),
    ]
